# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

intersectSorted <- function(vec1, vec2) {
    .Call('WCM_intersectSorted', PACKAGE = 'WCM', vec1, vec2)
}

unionSorted <- function(vec1, vec2) {
    .Call('WCM_unionSorted', PACKAGE = 'WCM', vec1, vec2)
}

setDiffSorted <- function(vec1, vec2) {
    .Call('WCM_setDiffSorted', PACKAGE = 'WCM', vec1, vec2)
}

complementSorted <- function(inds, maxInd) {
    .Call('WCM_complementSorted', PACKAGE = 'WCM', inds, maxInd)
}

intToUVec <- function(uint, length) {
    .Call('WCM_intToUVec', PACKAGE = 'WCM', uint, length)
}

zeroOneVecToInt <- function(zeroOneVec) {
    .Call('WCM_zeroOneVecToInt', PACKAGE = 'WCM', zeroOneVec)
}

intPow <- function(base, exponent) {
    .Call('WCM_intPow', PACKAGE = 'WCM', base, exponent)
}

permutations <- function(n) {
    .Call('WCM_permutations', PACKAGE = 'WCM', n)
}

orderStats <- function(M) {
    .Call('WCM_orderStats', PACKAGE = 'WCM', M)
}

partialTauStar <- function(X, Y) {
    .Call('WCM_partialTauStar', PACKAGE = 'WCM', X, Y)
}

fullLexTauStarNaive <- function(X, Y) {
    .Call('WCM_fullLexTauStarNaive', PACKAGE = 'WCM', X, Y)
}

fullLexTauStarNaiveApprox <- function(X, Y, sims) {
    .Call('WCM_fullLexTauStarNaiveApprox', PACKAGE = 'WCM', X, Y, sims)
}

lexTauStarNaive <- function(X, Y, xPerm, yPerm) {
    .Call('WCM_lexTauStarNaive', PACKAGE = 'WCM', X, Y, xPerm, yPerm)
}

lexTauStarNaiveApprox <- function(X, Y, xPerm, yPerm, sims) {
    .Call('WCM_lexTauStarNaiveApprox', PACKAGE = 'WCM', X, Y, xPerm, yPerm, sims)
}

partialTauStarNaive <- function(X, Y) {
    .Call('WCM_partialTauStarNaive', PACKAGE = 'WCM', X, Y)
}

partialTauStarNaiveApprox <- function(X, Y, sims) {
    .Call('WCM_partialTauStarNaiveApprox', PACKAGE = 'WCM', X, Y, sims)
}

ism <- function(X, Y, xInds0, xInds1, yInds0, yInds1) {
    .Call('WCM_ism', PACKAGE = 'WCM', X, Y, xInds0, xInds1, yInds0, yInds1)
}

ismNaive <- function(X, Y, xInds0, xInds1, yInds0, yInds1) {
    .Call('WCM_ismNaive', PACKAGE = 'WCM', X, Y, xInds0, xInds1, yInds0, yInds1)
}

ismNaiveApprox <- function(X, Y, xInds0, xInds1, yInds0, yInds1, sims) {
    .Call('WCM_ismNaiveApprox', PACKAGE = 'WCM', X, Y, xInds0, xInds1, yInds0, yInds1, sims)
}

kendallsTauNaive <- function(X, Y) {
    .Call('WCM_kendallsTauNaive', PACKAGE = 'WCM', X, Y)
}

kendallsTauNaiveApprox <- function(X, Y, sims) {
    .Call('WCM_kendallsTauNaiveApprox', PACKAGE = 'WCM', X, Y, sims)
}

spearmansRhoNaive <- function(X, Y) {
    .Call('WCM_spearmansRhoNaive', PACKAGE = 'WCM', X, Y)
}

spearmansRhoNaiveApprox <- function(X, Y, sims) {
    .Call('WCM_spearmansRhoNaiveApprox', PACKAGE = 'WCM', X, Y, sims)
}

